language: php

php:
  - 8.0

branches:
  only:
  - /.*/

env:
  - GOOGLE_APPLICATION_CREDENTIALS=~/emptycredentials.json

before_script:
  - composer install -o -vvv --no-interaction
  - pecl install grpc-1.36.0RC1
  - pecl install protobuf
  - "sudo echo '{\"type\": \"authorized_user\",\"client_id\": \"\",\"client_secret\": \"\",\"refresh_token\": \"\"}' >> $GOOGLE_APPLICATION_CREDENTIALS"

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml
  - vendor/bin/phpcs --standard=phpcs_ruleset.xml -np

after_success:
  - bash <(curl -s https://codecov.io/bash)
