language: php

php:
  - 7.1
  - 7.2
  - 7.3

branches:
  only:
  - /.*/

env:
  - GOOGLE_APPLICATION_CREDENTIALS=/root/emptycredentials.json

before_script:
  - composer install
  - pecl install grpc
  - echo 'extension=grpc.so' >> $PHP_INI_DIR/conf.d/grpc.ini
  - echo '{"type": "authorized_user","client_id": "","client_secret": "","refresh_token": ""}' >> /root/emptycredentials.json

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --coverage-clover=coverage.xml
  - vendor/bin/phpcs --standard=phpcs_ruleset.xml -np

